### ISSUE TITLE
Intro to Capybara Tests

### ISSUE THREAD

**Issue by bhabig** [learn-co-students/intro-to-capybara-v-000#224]
ran tests after doing the code for the first half of the readme and got the following error:

Unable to activate sinatra-1.4.7, 
because rack-2.0.1 conflicts with rack (~> 1.5) (Gem::ConflictError)

removed .lock file, reran bundle install and got the same error. also tried 'bundle exec bundle install'

opened a question with Meredith and tried to solve the problem by altering the rack part of the Gemfile to look like this:

gem 'rack', '~> 2.0 '

but still get the exact same error, shown above. Googling this reveals it seems to be a common issue and it sounds like it could be a problem with Capybara.

**Comment by bhabig** [comment]
i was able to resolve this issue by running 'gem uninstall sinatra' and 'gem uninstall rack' (uninstalled all versions and said yes to every prompt). then, ran bundle install again.

**Comment by gj** [comment]
@pletcher –– I had the same problem. Uninstalling the Rack 2.0.1 gem and then re-running the tests worked for me.

**Comment by aturkewi** [comment]
Closing this issue because it is on a specific deploy of the lab and issues should be logged on the copy of the lab in `learn-co-curriculum`

Continuing to track this here: https://github.com/learn-co-curriculum/intro-to-capybara/issues/15
